Database
Raashul/medium-service pull request #4
Opened 2018-10-30 14:39 UTC by Sauasmast

Merged authentication and Post data implemented.

2018-10-31 00:26 UTC, Sauasmast commented
Added the ability to login through the use of the email address and password. Using the signup form. Will add local strategy to authenticate the user and assign the jwt token. Take a look and merge the file will you?

2018-11-01 07:08 UTC, Raashul requested changes
check how responses are dealt.

2018-11-01 07:11 UTC, Raashul requested changes
this is not good practise.

If(initloca)
....
if(passwordCheck) 

Simply reject from the promise and handle the rejected response using multiple ifs takes away the beauty of resolve reject in promises. check if this is possible without using ifs.

2018-11-23 20:36 UTC, Raashul approved these changes

2018-11-23 20:40 UTC, closed without merging